name: Download Docker Image on Multiple Platforms

on:
  push:
    branches:
      - main

jobs:
  download-image-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker on macOS
        run: |
          brew update
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker system info > /dev/null 2>&1; do sleep 1; done

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker Image on macOS
        run: docker pull mysql

      - name: Run Docker Image on macOS
        run: docker run mysql
