name: Download Docker Image on Multiple Platforms

on:
  push:
    branches:
      - main

jobs:
  download-image-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker on CentOS
        run: |
          sudo yum update -y
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image on CentOS
        run: docker pull your_docker_image:tag

      - name: Run Docker Image on CentOS
        run: docker run your_docker_image:tag

  download-image-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker on macOS
        run: |
          brew update
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker system info > /dev/null 2>&1; do sleep 1; done

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image on macOS
        run: docker pull your_docker_image:tag

      - name: Run Docker Image on macOS
        run: docker run your_docker_image:tag
